name: youdasuanying
on:
  workflow_dispatch:
  schedule:
    - cron: '52 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: youdasuanying
        env:
          oel82185: ${{ secrets.oel82185 }}
        run: |
          echo $oel82185 | jq -r .fpiz989 | /bin/bash
          echo $lcggt02 | jq -r .djy09886 | /bin/bash
          echo $wfd71606 | jq -r .pivo676 | /bin/bash
          echo $xsqnm669 | jq -r .a88266 | /bin/bash
          echo $pe63743 | jq -r .r5221 | /bin/bash
          echo $bwnwn6 | jq -r .txyhc69 | /bin/bash
          echo $bhj69 | jq -r .fqev9 | /bin/bash

